version: '3.8'

services:
  # Service สำหรับฐานข้อมูล PostgreSQL
  postgres:
    image: pgvector/pgvector:pg16 # แนะนำให้ใช้เวอร์ชันที่เจาะจงเพื่อความเสถียร
    container_name: plcnext-chatbot-postgres-1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: plcnextdb
    volumes:
      - plcnext-data:/var/lib/postgresql/data # เก็บข้อมูลฐานข้อมูลอย่างถาวร
      # --- บรรทัดที่สำคัญที่สุดที่ต้องเพิ่มเข้ามา ---
      - ./pgvector-init:/docker-entrypoint-initdb.d # รันสคริปต์ init.sql ตอนสร้างครั้งแรก
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Service สำหรับ LLM Server
  ollama:
    image: ollama/ollama:latest
    container_name: plcnext-chatbot-ollama-1
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  # Service สำหรับ Backend (API)
  backend:
    build: ./backend
    container_name: plcnext-chatbot-backend-1
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    volumes:
      - ./backend:/app
      - D:/65160250/NSC/plc_data/data/raw:/app/data/raw
      - D:/65160250/NSC/plc_data/data/Knowledge:/app/data/Knowledge
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/plcnextdb
      - OLLAMA_BASE_URL=http://ollama:11434
    restart: unless-stopped
    depends_on:
      - postgres
      - ollama

  # Service สำหรับ Frontend (UI)
  frontend:
    build: ./frontend
    container_name: plcnext-chatbot-frontend-1
    ports:
      - "5173:5173" # ถูกต้องสำหรับ Vite Dev Server
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - backend

# ประกาศ Volumes ที่จะใช้เก็บข้อมูลอย่างถาวร
volumes:
  plcnext-data:
  ollama_data:
